"""empty message

Revision ID: a813137b7435
Revises: bcdd1657bec4
Create Date: 2021-04-24 15:19:09.248290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a813137b7435'
down_revision = 'bcdd1657bec4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Venue_id', sa.Integer(), nullable=False),
    sa.Column('Artist_id', sa.Integer(), nullable=False),
    sa.Column('Start_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['Artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['Venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Artist_id','Venue_id','Start_time')
    )
    op.add_column('Artist', sa.Column('seeking_decription', sa.String(length=120), nullable=True))
    op.add_column('Artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.add_column('Artist', sa.Column('website', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('Venue', sa.Column('seeking_description', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('Venue', sa.Column('website', sa.String(length=120), nullable=True))


    op.execute(""" 
                    DELETE FROM public."Venue";
                    
                    INSERT INTO public."Venue" 
                    (
                    name,city,state,address, phone,image_link,facebook_link,
                    genres,seeking_description,seeking_talent,website
                    )
                    VALUES
                    (
                        'The Musical Hop',
                        'San Francisco',
                        'CA',
                        '1015 Folsom Street',
                        '123-123-1234',
                        'https://images.unsplash.com/photo-1543900694-133f37abaaa5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=400&q=60',
                        'https://www.facebook.com/TheMusicalHop',
                        '{"Jazz","Reggae","Swing","Classical","Folk"}',
                        'We are on the lookout for a local artist to play every two weeks. Please call us.',
                        TRUE,
                        'https://www.themusicalhop.com'
                    ),
                    (
                        'The Dueling Pianos Bar',
                        'New York',
                        'NY',
                        '335 Delancey Street',
                        '914-003-1132',
                        'https://images.unsplash.com/photo-1497032205916-ac775f0649ae?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80',
                        'https://www.facebook.com/theduelingpianos',
                        '{"Classical", "R&B", "Hip-Hop"}',
                        NULL,
                        FALSE,
                        'https://www.theduelingpianos.com'
                    ),
                    (
                        'Park Square Live Music & Coffee',
                        'San Francisco',
                        'CA',
                        '34 Whiskey Moore Ave',
                        '415-000-1234',
                        'https://images.unsplash.com/photo-1485686531765-ba63b07845a7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=747&q=80',
                        'https://www.facebook.com/ParkSquareLiveMusicAndCoffee',
                        '{"Rock n Roll", "Jazz", "Classical", "Folk"}',
                        NULL,
                        FALSE,
                        'https://www.parksquarelivemusicandcoffee.com'
                    );



    """)
    op.execute(""" 
                    DELETE FROM public."Artist";
                    
                    INSERT INTO public."Artist" 
                    (
                        name,city,state,phone,genres,image_link,facebook_link,
                        seeking_decription,seeking_venue,website
                    )
                    VALUES
                    (
                     'GUNS N PETALS',	
                     'San Francisco'	,
                     'CA',
                     '326-123-5000',
                     '{"Rock n Roll"}'	,
                     'https://images.unsplash.com/photo-1549213783-8284d0336c4f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=300&q=80',	
                     'https://www.facebook.com/GunsNPetals',
                     'Looking for shows to perform at in the San Francisco Bay Area!',
                     true,	
                     'https://www.gunsnpetalsband.com'
                     ),
                     (
                      'Matt Quevedo',
                      'New York',
                      'NY',
                      '300-400-5215',
                      '{"Jazz"}',
                      'https://images.unsplash.com/photo-1495223153807-b916f75de8c5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=334&q=80',
                      'https://www.facebook.com/mattquevedo923251523'	,
                      NULL,
                      FALSE,
                      NULL
                      ),
                      (
                      'The Wild Sax Band',
                      'San Francisco',
                      'CA',
                      '432-325-5432',
                      '{"Jazz","Classical"}',
                      'https://images.unsplash.com/photo-1558369981-f9ca78462e61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=794&q=80',
                      NULL	,
                      NULL,
                      FALSE,
                      NULL
                      );
    """)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'website')
    op.drop_column('Venue', 'seeking_talent')
    op.drop_column('Venue', 'seeking_description')
    op.drop_column('Venue', 'genres')
    op.drop_column('Artist', 'website')
    op.drop_column('Artist', 'seeking_venue')
    op.drop_column('Artist', 'seeking_decription')
    op.drop_table('Show')
    # ### end Alembic commands ###
